100=Replicator.__init__()
101=Le réplicateur a été initialisé.
102=Le fil d'execution du réplicateur a lancer l'erreur: {}\n{}
103=Le réplicateur {}

110=Replicator.run()
111=Le réplicateur à démarrer un fil d'execution avec l'id {}.
112=Le fil d'execution du réplicateur a été suspendu pour {} minutes.
113=Le fil d'execution du réplicateur a lancer l'erreur: {}\n{}

120=Replicator._synchronize()
121=D\u00e9marrage de la synchronisation des donn\u00e9es.
122=La synchronisation n'est pas possible le r\u00e9seau est hors ligne!!!
123=Fin de la synchronisation des donn\u00e9es.

200=Replicator._pullUsers()
201=D\u00e9marrage du t\u00e9l\u00e9chargement des donn\u00e9es pour l'utilisateur: {}.
202=Fin du t\u00e9l\u00e9chargement pour l'utilisateur: {}.
203=Le fil d'execution du réplicateur a lancer l'erreur: {}\n{}

210=Replicator._checkNewIdentifier()
211=L'utilisateur {} ne dispose plus que de {} identifiants, {} identifiants viennent d'être téléchargé.
212=A généré une erreur lors de la demande identifiants pour l'utilisateur {} avec le message: {}

220=Replicator._initUser()
221=Initialisation de l'utilisateur {}.
222=Première réplication de données pour l'utilisateur {}, terminée...

230=Replicator._pullUser()
231=L'utilisateur {} a #{} changements sur #{} pages avec le jeton {}.

300=Replicator._pushUsers()
301=D\u00e9marrage de la r\u00e9plication des donn\u00e9es pour l'utilisateur: {}.
302=A rencontr\u00e9 une erreur lors de la r\u00e9pliquation du fichier/r\u00e9p\u00e9rtoire: {} du {} portant l'Id: {}
303=Fin de la r\u00e9plication des donn\u00e9es pour l'utilisateur: {}.
304=Le fil d'execution du réplicateur a lancer l'erreur: {}\n{}

310=Replicator._pushItem
311=A repliqu\u00e9 la cr\u00e9ation du dossier: {} du {}
312=A repliqu\u00e9 la mise \u00e0 jour du titre du fichier/r\u00e9p\u00e9rtoire: {} du {}
313=A repliqu\u00e9 la mise \u00e0 jour de l'effacement du fichier/r\u00e9p\u00e9rtoire: {} du {}
314=Ne peut pas retrouver l'emplacement de la mise \u00e0 jour du fichier: {} la réponse HTTP est: {}
315=Ne peut pas retrouver l'emplacement de la mise \u00e0 jour du fichier: {}
316=Ne peut pas mettre \u00e0 jour le fichier: {} la réponse HTTP est: {}
317=A repliqué la création du fichier: {} du {} d'une taille de: {}
318=A repliqu\u00e9 la mise \u00e0 jour du fichier: {} du {} d'une taille de: {}
319=Le fil d'execution du réplicateur a lancer l'erreur: {}\n{}

400=DataBase.__init__()
401=DataBase: Chargement termin\u00e9
402=DataBase._mergeItem() size {} os name {}

410=DataBase.createDataBase()
411=Essaie de créer la base de données avec HsqlDB version: {}
412=Création réussie de la base de données
413=Impossible de créer la base de données : la version de HsqlDB installée: {} est inférieure à la version minimale prise en charge: {}

