100=Replicator.__init__()
101=Le réplicateur a été initialisé.
102=Le fil d'execution du réplicateur a généré l'erreur: {}\n{}

110=Replicator.run()
111=Le réplicateur à démarrer un fil d'execution avec l'id <{}>.
112=Le fil d'execution <{}> du réplicateur est suspendu pour <{}> minutes.
113=Le fil d'execution <{}> du réplicateur est arrêté.
114=Le fil d'execution <{}> du réplicateur a généré l'erreur: {}\n{}

120=Replicator._synchronize()
121=Démarrage de la synchronisation des données.
122=La synchronisation a été désactivée!!!
123=La synchronisation n'est pas possible le réseau est hors ligne!!!
124=Fin de la synchronisation des données.

130=Replicator._synchronizeUser()
131=Démarrage de la synchronisation des données pour l'utilisateur <{}>.
132=Fin de la synchronisation des données pour l'utilisateur <{}>.

200=Replicator._pullUser()
201=Démarrage de la réplication des données distantes pour l'utilisateur <{}>.
202=La réplication pour l'utilisateur <{}> a produit <{}> modifications dont <{}> téléchargements à l'aide de <{}> requête HTTP avec le jeton <{}>.
203=Fin de la réplication des données distantes pour l'utilisateur <{}>.
204=Le fil d'execution du réplicateur a généré l'erreur: {}\n{}

210=Replicator._checkNewIdentifier()
211=L'utilisateur <{}> ne dispose plus que de <{}> identifiants, <{}> identifiants viennent d'être téléchargé.
212=A généré une erreur lors de la demande identifiants pour l'utilisateur <{}> avec le message: {}

220=Replicator._initUser()
221=Démarrage de l'initialisation de l'utilisateur <{}>.
222=La synchronisation des documents partagés pour l'utilisateur <{}> a effectuée <{}> modifications dont <{}> téléchargements à l'aide de <{}> requête HTTP.
223=La première réplication pour l'utilisateur <{}> a effectuée <{}> modifications dont <{}> téléchargements à l'aide de <{}> requête HTTP avec le jeton <{}>.
224=Fin de l'initialisation de l'utilisateur <{}>.
225=Le fil d'execution du réplicateur a généré l'erreur: {}\n{}

300=Replicator._pushUsers()
301=Démarrage de la réplication des données locales pour l'utilisateur <{}>.
302=A rencontré une erreur lors de la répliquation du fichier/répértoire <{}> du <{}> portant l'Id <{}>
303=La réplication pour l'utilisateur <{}> a effectué <{}> modifications.
304=Fin de la réplication des données locales pour l'utilisateur <{}>.
305=Le fil d'execution du réplicateur a généré l'erreur: {}\n{}

310=Replicator._pushItem
311=A repliqué la création du dossier <{}> du <{}>.
312=A repliqué la mise à jour du titre du fichier/répértoire <{}> du <{}>.
313=A repliqué la mise à jour de l'effacement du fichier/répértoire <{}> du <{}>.
314=Erreur sur la requête <{}>: Ne peut pas retrouver l'emplacement de la mise à jour du fichier <{}> la réponse HTTP est <{}>.
315=Erreur sur la requête <{}>: Ne peut pas retrouver l'emplacement de la mise à jour du fichier <{}>.
316=Erreur sur la requête <{}>: Ne peut pas mettre à jour le fichier <{}> la réponse HTTP est <{}>.
317=A repliqué la création du fichier <{}> du <{}> d'une taille de <{}>.
318=A repliqué la mise à jour du fichier <{}> du <{}> d'une taille de <{}>.
319=Le fil d'execution du réplicateur a généré l'erreur: {}\n{}

400=DataBase.__init__()
401=DataBase: Chargement terminé
402=DataBase._mergeItem() size <{}> os name <{}>

410=DataBase.createDataBase()
411=Essaie de créer la base de données avec HsqlDB version <{}>.
412=Création réussie de la base de données.
413=Impossible de créer la base de données: la version de HsqlDB installée <{}> est inférieure à la version minimale prise en charge <{}>.

