100=Driver.__new__()
101=Initialisation du pilote <{}> terminée
102=ERREUR lors de l'initialisation du pilote <{}> suite à l'exception: {}

200=OptionsHandler.callHandlerMethod()
201=Une exception: {} inattendue s'est produite, produisant une série d'exceptions: {}

300=OptionsManager.__init__()
301=OptionManger a été correctement initialisé.

310=OptionsManager.loadSetting()
311=OptionManger a été correctement rechargé.

320=OptionsManager.saveSetting()
321=OptionManger a sauvegardé des options {} et la journalisation {}.


1000=ERREUR d'URL de connection
1001=ERREUR d'authentification
1002=ERREUR d'authorisation
1003=ERREUR d'installation
1004=ERREUR réseau
1005=ERREUR de base de données
1006=ERREUR de fournisseur


1100=Driver.__init__()
1101=Initialisation du pilote terminé

1110=Driver.connect()
1111=Chargement du pilote pour l'URL: {}
1112=Le protocole <{}> est invalide.
1113=Le compte utilisateur et/ou le mot de passe est invalide.
1114=Le compte utilisateur <{}> est invalide.
1115=La version {} de la base de données Hsqldb est chargée, l'utilisateur {} est connecté.
1116=Une erreur <{}> s'est produite lors de la connexion avec comme trace <{}>.


1200=DataSource.__init__()
1201=La source de données est en cours de chargement...
1202=Chargement réussi de la source de données.

1250=DataBase.__init__()
1251=La base de données n'existe pas, création d'une nouvelle base de données.
1252=La création de la base de données a réussi.


1400=DataSource.getConnection()
1401=L'utilisateur {} a abandonné l'assistant d'autorisation OAuth2, l'extension {} ne peut pas continuer sans cette autorisation!!!


1500=User.__init__()
1501=L'utilisateur <{}> est en cours de chargement...
1502=Recherche de l'utilisateur <{}> dans la base de données.
1503=L'utilisateur <{}> existe dans la base de données. Tentative de connexion au fournisseur.
1504=L'utilisateur <{}> n'existe pas dans la base de données. Tentative de connexion au fournisseur.
1505=Chargement réussi pour l'utilisateur <{}>.
1506=L'utilisateur {} a abandonné l'assistant d'autorisation OAuth2, l'extension {} ne peut pas continuer sans cette autorisation!!!
1507=Impossible de se connecter au serveur <{}>. Le réseau est-il hors ligne?
1508=Can't insert user {} in DataBase


1600=Provider.raiseForStatus()
1601=La requête HTTP <{}> a renvoyé le code d'état {} pour l'utilisateur {} sur l'URL {} avec le contenu {}

1610=Provider.initUserBooks()
1611=Impossible de récupérer le carnet d'adresses pour l'utilisateur {}, le serveur {} ne prend pas en charge les carnets d'adresses!!!

1620=Provider._getDiscoveryUrl()
1621=La requête HTTP <{}> pour l'utilisateur {} sur l'URL {} ne peut retrouver <Location> dans les en-têtes HTTP {}
1622=Malgré {} tentatives, impossible de trouver une url de découverte autre que: {}

1640=Provider._getNewUserId()
1641=L'utilisateur {} avec le mot de passe {} ne peut pas se connecter au serveur {} sur l'URL {}
1642=L'utilisateur {} ne trouve pas sur l'URL {} de serveur compatible CardDAV

1650=Provider._supportAddressbook()
1651=La requête HTTP <{}> pour l'utilisateur {} sur l'URL {} ne peut retrouver <DAV> dans les en-têtes HTTP {}

1660=Provider._getAddressbooksUrl()
1661=La requête HTTP <{}> pour l'utilisateur {} sur l'URL {} ne peut pas analyser le contenu {}


1700=helper.checkConfiguration()
1701=L'extension {} est introuvable. Vous devez installer cette extension pour utiliser {}.
1702=La version {} de l'extension {} est obsolète. Vous devez mettre à jour cette extension vers la version {}.
1703={} ne dispose pas du niveau d'API nécessaire pour créer la base de données {}. Ce niveau devrait être : <com.sun.star.sdb>

