100=dbqueries.py -> getSqlQuery()
101=ERROR: Query '%s' not found!!!

110=dbtools -> checkDataBase()
111=DataBase ERROR
112=Hsqldb database driver: %s is not the correct version!!!\nHsqldb requiered driver version: %s - loaded version: %s

200=wizard.py -> initialize()
201=Arguments are not a sequence or its length is not two
202=PageIds is not a sequence or its length is too short (ie: less than two)
203=Controller does not have the right interfaces (ie: com.sun.star.ui.dialogs.XWizardController)
210=wizard.py -> enablePage()
211=The page cannot be deactivated because it is currently active
212=There is no page with the given ID in the current path
220=wizard.py -> enablePage()
221=There is no path with the given index
222=The path cannot be activated in the current state of the wizard

300=contentprovider.py -> __init__()
301=ContentProvider: %s Loading completed
310=contentprovider.py -> registerInstance()
311=Scheme/Plugin: %s/%s ... Started
312=Scheme/Plugin: %s/%s ... Completed
320=contentprovider.py -> _getUser()
321=Unable to parse URI from an invalid URL: %s
322=Unable to retrieve URI from an incomplete URL: %s
323=Unable to retrieve username from URL: %s
330=contentprovider.py -> createContentIdentifier()
331=Identifier: %s ... Completed
340=contentprovider.py -> queryContent()
341=Identitifer: %s ... cannot be found: %s
342=Identitifer: %s ... Completed
350=contentprovider.py -> compareContentIds()
351=Identifiers: %s - %s ... seem to be the same
352=Identifiers: %s - %s ... doesn't seem to be the same
360=contentprovider.py -> deregisterInstance()
361=Scheme: %s ... Completed
370=contentprovider.py -> __del__()
371=%s unloading ... Completed

400=user.py -> __init__()
401=User loading completed

500=identifier.py -> __init__()
501=Identifier loading completed
510=identifier.py -> getDocumentContent()
511=ERREUR: %s - %s

600=datasource.py -> _initializeUser()
601=Service: %s is not available... Check your installed extensions!!!
602=Can't insert User: %s in DataBase
603=User: %s does not exist at this Provider
604=Can't retrieve User: %s from provider: network is OffLine!!!

700=replicator.py -> _synchronize()
701=Synchronization is not possible network is offline!!!
710=replicator.py -> _syncData()
711=Start synchronization for user: %s at %s
712=Stop synchronization for user: %s at %s
720=replicator.py -> _initUser()
721=Import of Files/Directory by %s requests containing %s elements producing %s insertion/updates
722=%s orphan File/Directory could not be imported!!! See the following details...
723=The File/Directory: %s identified with the ID: %s, seems orphan, its parents: %s could not be identified!
730=replicator.py -> _pushItem
731=Has replicated the creation of a folder: %s of %s
732=Has replicated the creation of a file: %s of %s
733=Has replicated the file/folder's title: %s update of %s
734=Has replicated the file: %s of %s size: %s
735=Has replicated the file/folder's trashed: %s of %s
736=Has encountered an error while replicating the file/folder: %s of %s with Id: %s
